# Simple Makefile for final_project_c
CC = gcc
CFLAGS = -Wall -Wextra -pedantic -std=c90

SRC = main.c \
      util.c \
      labels.c \
      table.c \
      pre_assembly.c \
      ordering_into_table.c \
      binary_table_parsing.c \
      file_formating.c

OBJ = $(SRC:.c=.o)

TARGET = assembler

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJ)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ) $(TARGET)
